name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  country_code_picker: ^3.3.0
  country_list: ^0.0.5
  country_picker: ^2.0.27
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  turn_page_transition: ^0.4.0
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Chomsky
      fonts:
        - asset: assets/fonts/Chomsky.otf
    - family: NYTCheltenhamNormal
      fonts:
        - asset: assets/fonts/nyt-cheltenham-normal.ttf
    - family: NYTCheltenhamBold
      fonts:
        - asset: assets/fonts/nyt-cheltenham-bold.ttf
  assets:
    - assets/images/
    
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"